apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataflow-operator.fullname" . }}
  labels:
    {{- include "dataflow-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.webhook.enabled }}
    - port: 9443
      targetPort: webhook
      protocol: TCP
      name: webhook
    {{- end }}
  selector:
    {{- include "dataflow-operator.selectorLabels" . | nindent 4 }}
