{{- if and .Values.webhook.enabled .Values.webhook.caBundle }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "dataflow-operator.fullname" . }}
  labels:
    {{- include "dataflow-operator.labels" . | nindent 4 }}
webhooks:
  - name: vdataflow.dataflow.dataflow.io
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - dataflow.dataflow.io
        apiVersions:
          - v1
        resources:
          - dataflows
        scope: Namespaced
    clientConfig:
      service:
        name: {{ include "dataflow-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-dataflow-dataflow-io-v1-dataflow
      caBundle: {{ .Values.webhook.caBundle }}
{{- end }}
